# Generated by Django 5.0.1 on 2025-10-07 10:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('original_video', models.FileField(upload_to='videos/original/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])], verbose_name='Video Originale')),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='videos/processed/', verbose_name='Video Processato')),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('processing', 'In Elaborazione'), ('completed', 'Completato'), ('failed', 'Fallito')], default='pending', max_length=20, verbose_name='Stato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('total_frames', models.IntegerField(default=0, verbose_name='Frame Totali')),
                ('processed_frames', models.IntegerField(default=0, verbose_name='Frame Processati')),
                ('detections_count', models.IntegerField(default=0, verbose_name='Numero Rilevazioni')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Messaggio Errore')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Task ID')),
            ],
            options={
                'verbose_name': 'Rilevazione Video',
                'verbose_name_plural': 'Rilevazioni Video',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField(verbose_name='Numero Frame')),
                ('class_name', models.CharField(max_length=100, verbose_name='Classe')),
                ('confidence', models.FloatField(verbose_name='Confidenza')),
                ('bbox_x1', models.FloatField(verbose_name='BBox X1')),
                ('bbox_y1', models.FloatField(verbose_name='BBox Y1')),
                ('bbox_x2', models.FloatField(verbose_name='BBox X2')),
                ('bbox_y2', models.FloatField(verbose_name='BBox Y2')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('video_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='detection.videodetection')),
            ],
            options={
                'verbose_name': 'Rilevazione',
                'verbose_name_plural': 'Rilevazioni',
                'ordering': ['frame_number'],
                'indexes': [models.Index(fields=['video_detection', 'frame_number'], name='detection_d_video_d_42d633_idx')],
            },
        ),
    ]
