# Generated by Django 5.0.1 on 2025-11-06 17:32

import detection.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
        migrations.AlterField(
            model_name='videodetection',
            name='original_video',
            field=models.FileField(upload_to=detection.models.original_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])], verbose_name='Video Originale'),
        ),
        migrations.AddIndex(
            model_name='videodetection',
            index=models.Index(fields=['user', 'created_at'], name='detection_v_user_id_c46432_idx'),
        ),
    ]
